export const cartProductsData = [
  {
    "id": 1,
    "name": "Футболка UZcotton мужская",
    "image": "https://basket-05.wb.ru/vol976/part97622/97622981/images/c516x688/1.webp",
    "color": "белый",
    "size": "56",
    "warehouse": "Коледино WB",
    "deliverer": "ООО Вайлдберриз",
    "delivererNumber": "ОГРН: 1067746062449",
    "delivererAddress": "142181, Московская область, д Коледино, тер. Индустриальный Парк Коледино, д. 6 стр. 1",
    "quantity": 1,
    "price": 522,
    "oldPrice": 1051,
    "remainingGoods": 2,
    "isSelected": false,
    "isLiked": false
  },
  {
    "id": 2,
    "name": "Силиконовый чехол картхолдер (отверстия) для карт, прозрачный кейс бампер на Apple iPhone XR, MobiSafe",
    "image": "https://basket-03.wb.ru/vol301/part30168/30168856/images/big/1.webp",
    "color": "прозрачный",
    "size": "",
    "warehouse": "Коледино WB",
    "deliverer": "OOO Мегапрофстиль",
    "delivererNumber": "ОГРН: 5167746237148",
    "delivererAddress": "129337, Москва, улица Красная Сосна, 2, корпус 1, стр. 1, помещение 2, офис 34",
    "quantity": 200,
    "price": 10500,
    "oldPrice": 2300047,
    "remainingGoods": 999,
    "isSelected": false,
    "isLiked": false
  },
  {
    "id": 3,
    "name": "Карандаши цветные Faber-Castell \"Замок\", набор 24 цвета, заточенные, шестигранные, Faber-Castell",
    "image": "https://www.hudozhnik.club/img/faber-castell/big/120124.jpg",
    "color": "",
    "size": "",
    "warehouse": "Коледино WB",
    "deliverer": "OOO Вайлдберриз",
    "delivererNumber": "ОГРН: 1067746062449",
    "delivererAddress": "142181, Московская область, д Коледино, тер. Индустриальный Парк Коледино, д. 6 стр. 1",
    "quantity": 2,
    "price": 247,
    "oldPrice": 950,
    "remainingGoods": 2,
    "isSelected": false,
    "isLiked": false
  },
];
